#!/bin/sh
# /data/local-ai/asgard/e2e-tasks.sh - the four E2E coding tasks (sourced by e2e-test.sh). Difficulty ladder:
#   rust  (easy)    string reverse by chars + unit tests
#   go    (medium)  wordfreq: Unicode word counting from stdin, case folding, -n flag, deterministic ordering, tests
#   c     (harder)  bignum: arbitrary-precision signed + - * on decimal strings, --selftest, Makefile, -Werror, ASan-clean
#   asm   (hardest) b64: streaming base64 encoder + decoder (-d) in x86-64 GNU as, FreeBSD syscalls, no libc, argv
#                   parsing, short read/write handling, input validation; the prompt carries a 700-line acceptance-vector
#                   file (~57K tokens) on stdin, so the session starts at ~80K context and the multi-turn work
#                   (code, builds, test output, fixes) is expected to carry it well past 128K — a long-context test
#                   where most of the window is filled by the model's own work, not by the input.
# e2e_prompt TASK            -> prints the prompt
# e2e_prepare TASK WORKDIR   -> creates task input files in WORKDIR, prints the path of a file to feed on stdin
#                               (or nothing)
E2E_TASKS="rust go c asm"
ASM_VECTOR_LINES=${ASM_VECTOR_LINES:-700}

e2e_prompt() {
  case $1 in
  rust) echo 'Create a Rust cargo project named revstr in the current directory (write Cargo.toml and src/main.rs yourself or use cargo new). Implement pub fn reverse(s: &str) -> String that reverses a string by Unicode scalar values (chars), not bytes, and a main() that reads all of stdin, strips one trailing newline, and prints the reversed string followed by a newline. Add unit tests for: the empty string, "hello" -> "olleh", the Polish string "Zażółć gęślą jaźń", and an emoji string. No external crates. Run `cargo build --release` and `cargo test` and fix any errors until both pass. Finish by printing the final src/main.rs.' ;;
  go) echo 'Create a Go module named wordfreq in the current directory (run `go mod init wordfreq`; standard library only, no external modules). Write a command-line program that reads all of standard input as UTF-8 text and prints the N most frequent words. Definitions: a word is a maximal run of Unicode letters and/or digits (unicode.IsLetter || unicode.IsDigit); every other character (spaces, punctuation, underscore, newlines, ...) separates words; words are compared and printed in their strings.ToLower form. Output: one line per word of the form "<count>\t<word>" (the count, a TAB, the word), sorted by count descending, ties broken by the word ascending using plain Go string comparison. Flag -n N (default 10) limits the number of lines; N < 1 is an error: print a message to stderr and exit with status 2; print fewer lines if there are fewer distinct words; empty input prints nothing and exits 0. Put the tokenizing+counting and the sorting into functions with table-driven unit tests (`go test`) covering at least: empty input, case folding, punctuation and newlines as separators, digits, the Polish text "Zażółć gęślą jaźń, zażółć!" and the tie-break order. Run `go vet ./...`, `go build` and `go test ./...` and fix everything until all pass. Finish by printing the final main.go.' ;;
  c) echo 'Create a C11 project named bignum in the current directory: bignum.c plus a Makefile with the targets all (default), test and clean that works with both BSD make and GNU make. It must compile without any warning using: cc -std=c11 -Wall -Wextra -Werror -O2 -o bignum bignum.c. The program reads standard input line by line; empty lines are skipped; every other line has the form "<A> <op> <B>" (single spaces) where A and B are decimal integers with an optional leading minus sign and up to 10000 digits, and op is one of + - *. For each such line print the exact result on its own line as a canonical decimal integer (no leading zeros, never "-0", zero is "0"). Implement the arithmetic yourself (schoolbook algorithms are fine) with dynamically allocated memory and no fixed size limits, and free everything (the program must run clean under -fsanitize=address,undefined). A malformed line prints the single word "error" and processing continues; exit status 0 at EOF. Add a --selftest mode that checks at least 20 built-in cases with assert (negative numbers, zero, carries and borrows, unequal lengths, a-b with |b|>|a|, and one product of two 100-digit numbers with a known result) and prints "selftest ok"; `make test` must build and run --selftest. Run `make` and `make test` and fix all errors until they pass. Finish by printing the final bignum.c.' ;;
  asm) echo 'Write an x86-64 assembly program for FreeBSD in one file b64.s using GNU as (AT&T syntax; assemble with `as b64.s -o b64.o` and link with `ld -o b64 b64.o`; GNU as 2.44 is /usr/local/bin/as). No libc: use FreeBSD system calls directly (numbers are in /usr/include/sys/syscall.h; FreeBSD x86-64 convention: number in %rax, arguments in %rdi %rsi %rdx, the `syscall` instruction, and on error the carry flag is set with errno in %rax; at _start the stack holds argc and argv). Behaviour: `./b64` reads arbitrary binary data from standard input until EOF and writes its base64 encoding (RFC 4648 standard alphabet A-Z a-z 0-9 + /, "=" padding, no line breaks, no trailing newline) to standard output and exits with status 0. `./b64 -d` does the reverse: reads base64 text from standard input until EOF, ignores newline characters anywhere in the input, decodes it and writes the raw bytes to standard output, exit status 0; on any other invalid character, wrong padding or a length that is not a multiple of 4 it exits with status 1. Any other argument prints a one-line usage message to standard error and exits with status 2. Both directions must handle any input size including empty input; read() may return fewer bytes than requested, so process complete groups (3 input bytes when encoding, 4 characters when decoding) and carry the leftover bytes over to the next read; write() may return a short count, so loop until everything is written; exit with status 1 if read or write fails. The file VECTORS.txt in the current directory holds the acceptance test vectors, one per line: the raw bytes in lowercase hex, a TAB, their base64 encoding (an empty hex field means empty input); its complete content is included above for your reference - do not print it again. Add a Makefile with the targets all (default), test and clean, and a test.sh (POSIX sh, may use python3) that runs every vector through ./b64 in both directions (hex -> base64 with ./b64, base64 -> hex with ./b64 -d) and prints the numbers of passed and failed checks; `make test` must run it. Run `make` and `make test` and fix everything until all checks pass. Finish by printing the final b64.s.' ;;
  *) echo "unknown task '$1' (rust|go|c|asm)" >&2; return 1 ;;
  esac
}

e2e_prepare() {
  d=$(dirname "$(realpath "$0")")
  case $1 in
  asm) python3 "$d/e2e-vectors.py" "$ASM_VECTOR_LINES" "$2/VECTORS.txt" || return 1
       { echo "Acceptance test vectors (VECTORS.txt, $ASM_VECTOR_LINES lines, format: <hex input>TAB<expected base64>):"; cat "$2/VECTORS.txt"; echo; echo "--- end of VECTORS.txt ---"; echo; } > "$2/.stdin.txt"
       echo "$2/.stdin.txt" ;;
  *) : ;;
  esac
}
